### ISSUE TITLE
SUNO_COOKIE Error

### ISSUE THREAD

**Issue by gerrycola** [gcui-art/suno-api#156]
hello all! I'm sorry to be another one to add to the cookie errors. I swear i have taken the time to go through the other issues, but i unfortunately have not found a solution.

So I: Cloned and deployed the project locally, and at first i was getting my cookie info by following the steps in the video, but like others, since the beginning of my cookie looks different from the video, I most recently used a function shared by a nice user in the console of firefox to get the cookie. I'm not sure what to and what not to share here in the group, I assume i shouldn't share my full cookie, but i still can't really tell if it's the full cookie or if there is extra stuff at the beginning, but i have tried running the program by chopping of bits from the beginning, but to no avail. 

The error i receive i'll end up receiving:

and in VS code console i run `npm run dev` and see this:
![image](https://github.com/user-attachments/assets/7733bf7b-eb71-4a7c-be0a-e19ad3bb6c01)

then i go to: http://localhost:3000/api/get_limit

and:

from: http://localhost:3000/api/get_limit
error | "Internal server error. Error: Failed to get session id, you may need to update the SUNO_COOKIE"

and in my console i get this:

```
○ Compiling /api/get_limit ...
 ✓ Compiled /api/get_limit in 3.3s (215 modules)
Error fetching limit: Error: Failed to get session id, you may need to update the SUNO_COOKIE
    at SunoApi.getAuthToken (webpack-internal:///(rsc)/./src/lib/SunoApi.ts:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SunoApi.init (webpack-internal:///(rsc)/./src/lib/SunoApi.ts:48:9)
    at async newSunoApi (webpack-internal:///(rsc)/./src/lib/SunoApi.ts:324:12)
    at async GET (webpack-internal:///(rsc)/./src/app/api/get_limit/route.ts:17:34)
    at async C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:63809
    at async eU.execute (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53964)
    at async eU.handle (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:65062)
    at async doRender (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:1317:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:1539:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:1447:28)
    at async DevServer.renderPageComponent (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:1844:24)
    at async DevServer.renderToResponseImpl (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:1882:32)
    at async DevServer.pipeImpl (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\next-server.js:269:17)
    at async DevServer.handleRequestImpl (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\base-server.js:791:17)
    at async C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\dev\next-dev-server.js:331:20
    at async Span.traceAsyncFn (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\trace\trace.js:151:20)
    at async DevServer.handleRequest (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\dev\next-dev-server.js:328:24)
    at async invokeRender (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (C:\Users\mrgre\Documents\Suno_AI_Prototype_Shit\suno-api\node_modules\next\dist\server\lib\start-server.js:140:13)
    ```
    
    i don't know if this is enough to get help, but please help my friends! I have to make a capstone project for school, my goal is to build a "band in a box" device, and one of the features that i really think would level up this project is if I could integrate AI generated music! my excitement level is peaking haha!

**Comment by kutaybuyukkorukcu** [comment]
Does your cookie starts with ajs_anonymous_id? To me different sign in options gave me different cookies. In my case, I've removed the parts before 'client' and it worked.

**Comment by gerrycola** [comment]
HEy @kutaybuyukkorukcu yes one version did for sure (i say one version because firefox cookie and chrome cookie looked a little weird, i think i opted for firefox because google had the word "anonymous" in it and that made me uneasy since i am trying to identity myself to the service haha)

I tried chopping off text up to client, if i recall there were two times that it looked like it was saying "__client" near the top, which one did you remove up to?

maybe i just need a fresh start and see how it goes. 

Thanks for your reply! i hope what i'm saying makes sense cuz it's from memory at the moment hahaha

**Comment by markus583** [comment]
Hi @gerrycola, do you recall how you logged in and which part you chopped off? For me, none of the login methods work since today.
