### ISSUE TITLE
Error generating music: Request failed with status code 500 without any changes in code

### ISSUE THREAD

**Issue by Alazka2k** [gcui-art/suno-api#164]
I suddenly get 500 when executing my code and don´t really know why. Maybe it´s not a bug, but someone can just help me. Thx.

This is the error log I get right now:

error: Error generating music: Request failed with status code 500 {"data":"{\n  \"error\": \"Internal server error\"\n}","headers":"{\n  \"access-control-allow-headers\": \"Content-Type, Authorization\",\n  \"access-control-allow-methods\": \"GET, POST, PUT, DELETE, OPTIONS\",\n  \"access-control-allow-origin\": \"*\",\n  \"cache-control\": \"public, max-age=0, must-revalidate\",\n  \"content-type\": \"application/json\",\n  \"date\": \"Thu, 26 Sep 2024 15:53:10 GMT\",\n  \"server\": \"Vercel\",\n  \"strict-transport-security\": \"max-age=63072000; includeSubDomains; preload\",\n  \"vary\": \"RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url\",\n  \"x-matched-path\": \"/api/custom_generate\",\n  \"x-vercel-cache\": \"MISS\",\n  \"x-vercel-id\": \"fra1::iad1::q6ml4-1727365988525-b54b929b5238\",\n  \"transfer-encoding\": \"chunked\"\n}","stack":"AxiosError: Request failed with status code 500\n    at settle (C:\\Code\\Short-Video-Creator-Simplified\\node_modules\\axios\\dist\\node\\axios.cjs:2019:12)\n    at IncomingMessage.handleStreamEnd (C:\\Code\\Short-Video-Creator-Simplified\\node_modules\\axios\\dist\\node\\axios.cjs:3135:11)\n    at IncomingMessage.emit (node:events:532:35)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (C:\\Code\\Short-Video-Creator-Simplified\\node_modules\\axios\\dist\\node\\axios.cjs:4287:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MusicGenService.generateMusic (C:\\Code\\Short-Video-Creator-Simplified\\backend\\services\\music-service\\music-gen-service.js:38:24)\n    at async MusicServiceInterface.generateMusic (C:\\Code\\Short-Video-Creator-Simplified\\backend\\services\\music-service\\index.js:14:12)\n    at async runMusicGenTest (C:\\Code\\Short-Video-Creator-Simplified\\tests\\music-gen-test.js:97:28)","status":500}

Has someone an idea what is wrong?

**Comment by markus583** [comment]
Same here since today! Different accounts, browser, incognito, ... none help.
Could it be the cookie format?

**Comment by WendersonAmaroDeSouza** [comment]
I don't know if it's knowledge, but it worked when I removed the first items from the suno copied cookie.

I removed the highlighted part below

SUNO_COOKIE=**__client_uat=1234567890; __stripe_mid=abcdef12-3456-7890-abcd-1234567890ef123456; ajs_anonymous_id=1234abcd-5678-90ef-abcd-1234567890ab; _ga_7B0KEDD7XP=GS1.1.1234567890.12.1.1234567890.0.0.0;** _ga=GA1.1.1234567890.1234567890; __client_uat_U9tcbTPE=1234567890; __client=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsaWVudF8xMjM0NTZSSUdNd0ppNUZnTlk0NGs5c2pvZmI2R3ciLCJyb3RhdGluZ190b2tlbiI6Imdwb3V1dDdudXliaWV0Z3R2bjBkMmt5YXlzMDdhbGVieGp6OThvNHEifQ.mockedMockedUPmockedMocked.mockedmockedMockedMockedmockedMockedmockedMockedmocked; __cf_bm=Mocked12345MockedMockedMockedMockedMockedMockedMockedMockedMockedMockedMocked; _cfuvid=Mocked123456MockedMockedMockedMockedMockedMockedMockedMockedMockedMockedMocked; mp_26ced217328f4737497bd6ba6641ca1c_mixpanel=%7B%22distinct_id%22%3A%20%22mockedmockedmockedmockedmockedmockedmockedmocked%22%2C%22%24device_id%22%3A%20%22mockedmockedmockedmockedmockedmockedmockedmockedmockedmocked%22%2C%22%24search_engine%22%3A%20%22mocked%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fmocked.com%2F%22%2C%22%24initial_referring_domain%22%3A%20%22mocked.com%22%2C%22__mps%22%3A%20%7B%7D%2C%22__mpso%22%3A%20%7B%7D%2C%22__mpus%22%3A%20%7B%7D%2C%22__mpa%22%3A%20%7B%7D%2C%22__mpu%22%3A%20%7B%7D%2C%22__mpr%22%3A%20%5B%5D%2C%22__mpap%22%3A%20%5B%5D%2C%22%24user_id%22%3A%20%22mockedmockedmockedmockedmockedmockedmocked%22%7D
