### ISSUE TITLE
401 Authentication Error in keepAlive

### ISSUE THREAD

**Issue by andrew-stelmach** [gcui-art/suno-api#206]
Error stack is
```
Error fetching limit: Z [AxiosError]: Request failed with status code 401
    at eO (/app/.next/server/chunks/943.js:304:4037625)
    at IncomingMessage.<anonymous> (/app/.next/server/chunks/943.js:306:9463)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```

Endpoint is `https://clerk.suno.com/v1/client/sessions/[SESSION_ID]/tokens`, in the `keepAlive` method in `SunoApi.ts`, have updated to latest commit

**Comment by AlexTang0417** [comment]
{"error":"Internal server error. AxiosError: Request failed with status code 401"}

**Comment by angejr** [comment]
Same issue for me, for the same endpoint

**Comment by angejr** [comment]
With a ERR_BAD_REQUEST status code

**Comment by BareTread** [comment]
same for me

**Comment by JianYingJia** [comment]
I also encountered this problem, can you tell me how to solve it?

**Comment by gianmd** [comment]
Same here, anyone found a workaround?

**Comment by mattgk39** [comment]
I have this issue too.  I have tried Clerk version 4.74 to no avail.  Please help with this.

**Comment by TareefAzizi** [comment]
has anyone here found a work around?

**Comment by MiguelAraujo84** [comment]
same here..
